feat(log): add switch for colorful logging && change default logging color
Mrs4s/go-cqhttp pull request #1163
Opened 2021-11-14 18:06 UTC by Akegarasu

2021-11-14 18:13 UTC, Ink-33 approved these changes

2021-11-15 03:03 UTC, Mrs4s requested changes

2021-11-15 03:03 UTC, Mrs4s commented on modules/config/config.go
> +		LogColorful *bool   `yaml:"log-colorful"`
fmt一下

2021-11-15 16:44 UTC, Mrs4s approved these changes

2021-11-15 16:44 UTC, merged