feat: guild role API
Mrs4s/go-cqhttp pull request #1188
Opened 2021-11-22 18:32 UTC by Bluefissure

第一次写go……照虎画猫了属于是
如果有哪里写的不规范的希望能多多指教

2021-11-22 18:36 UTC, Mrs4s requested changes

2021-11-22 18:36 UTC, Mrs4s commented on coolq/api.go
> +	return OK(roles)
go-cqhttp 返回的数据都需要转换下命名规则, 请使用 `global.MSG` 构建

2021-11-22 18:36 UTC, Mrs4s commented on coolq/api.go
> +	return OK(role)
同上

2021-11-22 18:39 UTC, Mrs4s commented on coolq/api.go
> +// @route(set_user_role_in_guild)
最好使用 `set_guild_member_role` 保持统一性

2021-11-22 21:34 UTC, Bluefissure commented on coolq/api.go
> +	return OK(roles)
已更新

2021-11-22 21:34 UTC, Bluefissure commented on coolq/api.go
> +// @route(set_user_role_in_guild)
OK

2021-11-23 09:39 UTC, Mrs4s requested changes

2021-11-23 09:39 UTC, Mrs4s commented on coolq/api.go
> +// @route(modify_role_in_guild)
`update_guild_role`

2021-11-23 15:48 UTC, merged

2021-11-23 15:52 UTC, Bluefissure commented on coolq/api.go
> +// @route(modify_role_in_guild)
啊刚在睡觉才看到这个就发现已经被merge了（

2021-11-23 15:54 UTC, Mrs4s commented
以后别往 `master` pr了, 合到 `dev` 解决冲突累死人.
这次主要是要继续改功能, 就先合掉了, 不然后续会有一堆冲突

2021-11-23 16:01 UTC, Bluefissure commented
> 以后别往 `master` pr了, 合到 `dev` 解决冲突累死人. 这次主要是要继续改功能, 就先合掉了, 不然后续会有一堆冲突

哦草我推的是 `master`，没注意 ORZ
下次不会了