fix: should not use faststart flag before parse it
Mrs4s/go-cqhttp pull request #1248
Opened 2021-12-13 13:46 UTC by fzls

目前设计上仅在未设置FastStart标记时，才会检查RunningByDoubleClick。
https://github.com/Mrs4s/go-cqhttp/blob/7278f99ed9118fe2e54aca752e62574d5bae3f00/cmd/gocq/main.go#L46-L53

但是由于目前代码中实际上在更后面的地方才解析FastStart标记，会导致这里这个判断永远没有作用。
https://github.com/Mrs4s/go-cqhttp/blob/7278f99ed9118fe2e54aca752e62574d5bae3f00/cmd/gocq/main.go#L117-L118

pr中将这段逻辑移到了解析的地方之后，也可以选择把解析FastStart的代码往前移

2021-12-13 14:00 UTC, Ink-33 commented
双击检查应当早于任何会产生错误的逻辑，而解析`faststart`前会有创建缓存目录错误，db 打开错误，配置文件解析错误。

当时提前这一段是因为配置文件出现了类型错误 ( int 误写为 string 等) 时会直接退出，所以提前到了`base.Init()`前

这里给你提供几点修改思路
1. 改动`faststart`的解析顺序，使他解析前不会产生有报错的逻辑
2. 将解析`key`和`faststart`的逻辑做到`internal/base`包里面，在调用`base.Parse()'后紧跟双击检查

2021-12-13 14:05 UTC, Ink-33 requested changes
See my comment.

2021-12-14 07:56 UTC, fzls commented
> 双击检查应当早于任何会产生错误的逻辑，而解析`faststart`前会有创建缓存目录错误，db 打开错误，配置文件解析错误。
> 
> 当时提前这一段是因为配置文件出现了类型错误 ( int 误写为 string 等) 时会直接退出，所以提前到了`base.Init()`前
> 
> 这里给你提供几点修改思路
> 
> 1. 改动`faststart`的解析顺序，使他解析前没有会产生报错的逻辑
> 2. 将解析`key`和`faststart`的逻辑做到`internal/base`包里面，在调用`base.Parse()'后紧跟双击检查

改为将faststart解析流程往前移了

2021-12-14 09:44 UTC, Ink-33 approved these changes

2021-12-14 11:54 UTC, wdvxdr1123 commented
我觉得这应该算是一个设计失误， faststart 应该为一个 flag， 而不是程序的子命令

2022-02-06 08:05 UTC, wdvxdr1123 commented
已在 f88f51ceed3665942e9da3b507640c11e1c65d5d 中更改为flag

2022-02-06 08:05 UTC, closed without merging