feat: add redis database support
Mrs4s/go-cqhttp pull request #1972
Opened 2023-03-12 17:56 UTC by JustAnotherID

2023-03-13 02:15 UTC, wdvxdr1123 commented on db/redis/redis.go
> +	GocqhttpGuildChannelMsgKey = "GOCQHTTP_GUILD_CHANNEL_MSG:"
非导出，我认为应该是groupMsgKeyPrefix

2023-03-13 02:15 UTC, wdvxdr1123 commented on db/redis/redis.go
> +	"gopkg.in/yaml.v3"
goimports

2023-03-13 02:15 UTC, wdvxdr1123 commented on db/redis/redis.go
> +			}
同样检查Host？默认用127.0.0.1？或者直接fatal？

2023-03-13 02:15 UTC, wdvxdr1123 commented on db/redis/redis.go
> +	r.ctx = &ctx
为什么需要保存Context?

2023-03-13 02:15 UTC, wdvxdr1123 commented on db/redis/redis.go
> +	result, err := r.rdb.Get(*r.ctx, GocqhttpGroupMsgKey+strconv.Itoa(int(id))).Result()
这里应该是context.Backgroud(), 考虑添加超时逻辑？下面的一样。

2023-03-13 06:03 UTC, JustAnotherID commented on db/redis/redis.go
> +	GocqhttpGuildChannelMsgKey = "GOCQHTTP_GUILD_CHANNEL_MSG:"
好的，我调整一下

2023-03-13 06:15 UTC, JustAnotherID commented on db/redis/redis.go
> +	result, err := r.rdb.Get(*r.ctx, GocqhttpGroupMsgKey+strconv.Itoa(int(id))).Result()
是的，超时逻辑已经加上了

2023-03-13 08:53 UTC, wdvxdr1123 commented on db/redis/redis.go
> +	Timeout time.Duration `yaml:"timeout"`
time.Duration单位是nano second， 不方便使用

2023-03-13 11:46 UTC, JustAnotherID commented on db/redis/redis.go
> +	Timeout time.Duration `yaml:"timeout"`
ok，调整为毫秒了

2023-03-18 04:05 UTC, fumiama requested changes
你有试过json确实可行吗？在sqlite中，我选择用yaml存了message的Content, 因为json反序列化[]global.MSG时，会将所有数字变为float64😂，虽然我也给对应位置增加了float转int，但是不保证能照顾到所有情况（包括之后可能出现的情况）。

2023-03-18 08:39 UTC, JustAnotherID commented
> 你有试过json确实可行吗？在sqlite中，我选择用yaml存了message的Content, 因为json反序列化[]global.MSG时，会将所有数字变为float64😂，虽然我也给对应位置增加了float转int，但是不保证能照顾到所有情况（包括之后可能出现的情况）。

我在测试的时候没碰上序列化问题😂

2023-03-21 11:42 UTC, wdvxdr1123 commented
> 我在测试的时候没碰上序列化问题😂自用的bot切换到redis以后也没出现什么状况
潜在的问题是int64转换为float64后，有效范围变为了int53(频道相关的会受影响)

2023-08-08 12:41 UTC, JustAnotherID commented
一直卡在这也难受，如果yaml没有序列化问题那就切到yaml好了（）

2023-11-14 01:57 UTC, closed without merging