初步支持 cq:json消息，依赖 MiraiG的pr
Mrs4s/go-cqhttp pull request #221
Opened 2020-08-30 16:37 UTC by scjtqs

2020-08-30 16:50 UTC, Ink-33 commented
https://github.com/Mrs4s/MiraiGo/pull/36

2020-08-30 18:02 UTC, Ink-33 commented
我觉得这个转义可以程序内部实现

2020-08-31 00:33 UTC, scjtqs commented
这个不转义的麻烦在于，cq码的识别会被打断，会截取data前逗号，到下一个逗号处。当然，你们也可以后续调整优化解析策略啥的。



---原始邮件---
发件人: "Ink33"<notifications@github.com&gt;
发送时间: 2020年8月31日(周一) 凌晨2:03
收件人: "Mrs4s/go-cqhttp"<go-cqhttp@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"scjtqs"<scjtqs@qq.com&gt;;
主题: Re: [Mrs4s/go-cqhttp] 初步支持 cq:json消息，依赖 MiraiG的pr (#221)




 
我觉得这个转义可以程序内部实现
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-31 00:38 UTC, scjtqs commented
这个转义只是为了保证cq码的识别中别被中断而已。代码中，我又把他们转回正常的json状态的。要是cq码+正常json能被准确识别，那确实太好了。你可以试试，我里面加了个warming级别的日志用于打印接收到的json。

2020-08-31 00:52 UTC, Ink-33 commented
只转义那四个特定的符号比较麻烦，我想的是直接传入urlencode的json，这样不论是go-cqhttp还是机器人后端去处理json都比较方便

那个cq码识别似乎不太好搞，我目前只想到专门给CQ:json写一条正则的方法

2020-08-31 00:56 UTC, scjtqs commented
emmm urlencode的话应该也能过解析，不过有可能造成和其他cqhttp协议的不兼容性。cq码的那4个字符的转义，其实是酷q时代遗留的产物。你其实可以直接把json进行html实体化处理。那个转义就是这个意思，不过目前只针对那4个字符而已



---原始邮件---
发件人: "Ink33"<notifications@github.com&gt;
发送时间: 2020年8月31日(周一) 上午8:52
收件人: "Mrs4s/go-cqhttp"<go-cqhttp@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"scjtqs"<scjtqs@qq.com&gt;;
主题: Re: [Mrs4s/go-cqhttp] 初步支持 cq:json消息，依赖 MiraiG的pr (#221)




 
只转义那四个特定的符号比较麻烦，我想的是直接传入urlencode的json，这样不论是go-cqhttp还是机器人后端去处理json都比较方便
 
那个cq码识别似乎不太好搞，我目前只想到专门给CQ:json写一条正则的方法
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-31 00:58 UTC, scjtqs commented
甚至，你把整个json进行实体化处理后，影响也不大，甚至应该没有变化



---原始邮件---
发件人: "Ink33"<notifications@github.com&gt;
发送时间: 2020年8月31日(周一) 上午8:52
收件人: "Mrs4s/go-cqhttp"<go-cqhttp@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"scjtqs"<scjtqs@qq.com&gt;;
主题: Re: [Mrs4s/go-cqhttp] 初步支持 cq:json消息，依赖 MiraiG的pr (#221)




 
只转义那四个特定的符号比较麻烦，我想的是直接传入urlencode的json，这样不论是go-cqhttp还是机器人后端去处理json都比较方便
 
那个cq码识别似乎不太好搞，我目前只想到专门给CQ:json写一条正则的方法
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-31 01:02 UTC, Ink-33 commented
> emmm urlencode的话应该也能过解析，不过有可能造成和其他cqhttp协议的不兼容性。cq码的那4个字符的转义，其实是酷q时代遗留的产物。你其实可以直接把json进行html实体化处理。那个转义就是这个意思，不过目前只针对那4个字符而已
> 
> 
> 
> ---原始邮件---
> 发件人: "Ink33"<notifications@github.com&gt;
> 发送时间: 2020年8月31日(周一) 上午8:52
> 收件人: "Mrs4s/go-cqhttp"<go-cqhttp@noreply.github.com&gt;;
> 抄送: "Author"<author@noreply.github.com&gt;;"scjtqs"<scjtqs@qq.com&gt;;
> 主题: Re: [Mrs4s/go-cqhttp] 初步支持 cq:json消息，依赖 MiraiG的pr (#221)
> 
> 
> 
> 
>  
> 只转义那四个特定的符号比较麻烦，我想的是直接传入urlencode的json，这样不论是go-cqhttp还是机器人后端去处理json都比较方便
>  
> 那个cq码识别似乎不太好搞，我目前只想到专门给CQ:json写一条正则的方法
>  
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

保证兼容性的话就只能这样了
我去问问OneBot协议那边怎么处理转义的

2020-09-01 08:39 UTC, Mrs4s commented
这个PR等我隔壁改完再合

2020-09-02 07:25 UTC, Mrs4s requested changes
请兼容MiraiGo最新的提交.

2020-09-02 15:54 UTC, scjtqs commented
晚点我来瞧瞧你改了啥

2020-09-03 14:05 UTC, merged