fix sign server
Mrs4s/go-cqhttp pull request #2277
Opened 2023-07-06 05:07 UTC by liaosunny123

- 添加register Api
- 添加custom_energy的uin参数

PS：register使用的是默认密码，那个action似乎不能被更改，所以不知道怎么传入key

2023-07-06 05:36 UTC, liaosunny123 commented
`config.yaml`添加了一个`key`参数来获取与签名服务器匹对的密钥

2023-07-06 06:23 UTC, Fury94-Echo commented
赞美

2023-07-06 08:13 UTC, Mrs4s requested changes

2023-07-06 08:13 UTC, Mrs4s commented on cmd/gocq/login.go
> +	_, err := download.Request{
注册最好移动到初始化的时候

2023-07-06 08:27 UTC, liaosunny123 commented on cmd/gocq/login.go
> +	_, err := download.Request{
> 注册最好移动到初始化的时候

初始化这块的项目结构并不是很清楚，具体指的是在调用energy之前吗？
`internal/tlv/t544.go`
还是在其他地方

2023-07-06 08:29 UTC, rhwong commented
赞美

2023-07-06 09:29 UTC, kagangtuya-star commented
期待

2023-07-07 16:20 UTC, fatinghenji commented
期待

2023-07-10 06:42 UTC, closed without merging