修复TCP缓冲区不足问题；重构 qsign 签名服务对接部分；支持配置多个签名服务器
Mrs4s/go-cqhttp pull request #2389
Opened 2023-08-19 02:31 UTC by 1umine

配置文件有破坏性更新，使用先前的配置需要重新生成，此外需要确保签名服务和gocq至少有一个开启了自动注册配置
否则 `无法成功签名` ，配置默认自动注册为 `false` ，个人建议使用本地搭建的服务，并开启 qsign 自动注册。

## 更改
* SendSsoPacket 出错或返回空值时直接跳过提交 callback
* 开启自动注册时销毁实例若出错（真的丢失了必然是出错的）后不return，继续注册并重新签名。
* sign-server-timeout 配置改到了 Account 下，和其他签名服务相关配置放在一起。
* Authorization 不局限于使用 Bearer token。
* 重构：把签名请求的部分包装了一下，减少一些重复逻辑（如设置签名服务器地址，http authorization信息），并单独放在 qsign.go 内。
* 删除了连接签名服务时的 tcp ping，因新特性的实现在启动时会使用可用的签名服务器，没有则会提示相应错误。
* 删除了启动时的注册实例，新特性获取到可用签名服务器后会根据自动注册配置注册实例。

## 修复bug
fix #2368: 对于同一 timeout 的请求使用同一个 client，避免 `WithTimeout` 每次都创建新的 client 请求签名服务器并且在请求完成后没有关闭空闲连接，可能导致建立大量TCP连接导致TCP缓冲区空间不足或队列已满的问题。

## 新增功能
* 实现了部分 feature #2360 
  支持配置多个签名服务器，并可单独设置各签名服务器的 key 以及 auth 信息

2023-08-22 02:20 UTC, ShiaBox commented
谢谢佬，佬辛苦啦

2023-08-23 04:56 UTC, fumiama requested changes
good job.

2023-08-23 04:56 UTC, fumiama commented on cmd/gocq/qsign.go
> +func GetAvaliableSignServer() (config.SignServer, error) {
似乎并未有其它代码使用此函数，可使用小写，下面同。

2023-08-23 04:56 UTC, fumiama commented on cmd/gocq/qsign.go
> +var currentSignServer config.SignServer
可以使用`*config.SignServer`然后用atomic，就可以实现真正的原子操作。否则currentOK和currentSignServer分离，即使currentOK是atomic.Bool，仍然会有并发问题。最好也套一层函数封装，如
```go
type currentSignServer config.SignServer
func (c *currentSignServer) getxxx() ...
```

2023-08-23 04:56 UTC, fumiama commented on cmd/gocq/qsign.go
> +var errorCount = int64(0)
建议用uintptr

2023-08-23 04:56 UTC, fumiama commented on cmd/gocq/qsign.go
> +var signServers []config.SignServer
建议把对signServers的读写封装，如
```go
type signServers struct {
    ss []config.SignServer
    mu sync.Mutex
}
func (s *signServers) getxxxx() ...
```

2023-08-23 04:56 UTC, fumiama commented on cmd/gocq/qsign.go
> +		result := make(chan config.SignServer)
make(chan *config.SignServer)

2023-08-23 04:56 UTC, fumiama commented on cmd/gocq/qsign.go
> +		allDone := make(chan bool)
我建议用sync.WaitGroup，用chan复杂性太高且不易维护。

2023-08-23 04:56 UTC, fumiama commented on internal/download/download.go
> +var clients sync.Map
syncx.Map

2023-08-23 06:32 UTC, 1umine commented on cmd/gocq/qsign.go
> +		allDone := make(chan bool)
这里想过用wait group，不过不知道怎么控制在全部检查完了，但是还没超时时立即返回，同时在有一个检查完了后也立即返回（

2023-08-24 22:27 UTC, 1umine commented on cmd/gocq/qsign.go
> +		allDone := make(chan bool)
一开始也是这么干的，然后有人说配置太多时要检查好久😂

2023-08-24 22:39 UTC, 1umine commented on cmd/gocq/qsign.go
> +var signServers []config.SignServer
这个其实是启动时读取完配置后就不再动的，也需要封装吗（）

2023-08-25 13:54 UTC, fumiama commented on cmd/gocq/qsign.go
> +		allDone := make(chan bool)
那算了😂

2023-08-25 13:55 UTC, fumiama commented on cmd/gocq/qsign.go
> +var signServers []config.SignServer
统一一下代码风格😂

2023-08-25 13:55 UTC, fumiama commented
别忘了解决一下冲突

2023-08-25 23:26 UTC, 1umine commented on cmd/gocq/qsign.go
> +var signServers []config.SignServer
那把这个删了，直接用 `base.SignServers` ，就不另设变量获取行吗，和用其他配置一样的

2023-08-26 07:21 UTC, fumiama commented on cmd/gocq/qsign.go
> +var signServers []config.SignServer
确实，不并发之后就不用封装了。

2023-08-27 02:29 UTC, 1umine commented
应该可以了

2023-08-27 05:19 UTC, fumiama approved these changes

2023-08-27 05:19 UTC, merged

2023-08-28 14:52 UTC, Dreamail commented
[2023-08-28 22:49:57] [INFO]: 当前版本:(devel) 
[2023-08-28 22:49:57] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4dd2c0]

goroutine 1 [running]:
github.com/Mrs4s/go-cqhttp/cmd/gocq.getAvaliableSignServer()
	/build/cmd/gocq/qsign.go:72 +0x140
github.com/Mrs4s/go-cqhttp/cmd/gocq.LoginInteract()
	/build/cmd/gocq/main.go:166 +0x3f0
main.main()
	/build/main.go:20 +0x28

拉取了最新dev分支之后删除原配置重新配置依旧出现上述报错

2023-08-28 15:11 UTC, 1umine commented
用上一个 commit 的