admin api 初版
Mrs4s/go-cqhttp pull request #333
Opened 2020-09-30 12:14 UTC by scjtqs

2020-10-01 12:50 UTC, Mrs4s requested changes

2020-10-01 12:50 UTC, Mrs4s commented on server/apiAdmin.go
> +		picbase64 = base64.StdEncoding.EncodeToString(input)
此处应该可以将 captcha.jpg 作为静态资源返回，而不用base64以提高性能

2020-10-02 12:13 UTC, scjtqs commented
base64的话，只是webui上直接嵌入img标签显示方便点。做成url的话，还得新起一个api了。

2020-10-03 04:56 UTC, Mrs4s approved these changes

2020-10-03 04:57 UTC, merged