fix golangci-lint warning
Mrs4s/go-cqhttp pull request #572
Opened 2021-01-16 19:05 UTC by Ink-33

Fix:
- gosimple
- ineffassign
- staticcheck
- errcheck

Change `golang.org/x/crypto/ssh/terminal` to `golang.org/x/term`  because this package has been deprecated.

2021-01-17 08:49 UTC, Ink-33 commented
Still working. Do not merge.

2021-01-18 01:43 UTC, Mrs4s requested changes

2021-01-18 01:43 UTC, Mrs4s commented on global/fs.go
> +	//ImagePathOld 兼容旧版go-cqhtto使用的图片缓存目录
fix typo(

2021-01-18 04:38 UTC, Ink-33 commented on global/fs.go
> +	//ImagePathOld 兼容旧版go-cqhtto使用的图片缓存目录
ok i will(

2021-01-18 14:26 UTC, Mrs4s approved these changes

2021-01-18 14:27 UTC, merged