修复登录和重连逻辑，支持重连的验证码等处理，Fix #620
Mrs4s/go-cqhttp pull request #624
Opened 2021-02-08 20:01 UTC by qianjunakasumi

Fix #620 
测试了下应该没问题

2021-02-09 11:54 UTC, Ink-33 requested changes

2021-02-09 11:54 UTC, Ink-33 commented on server/apiAdmin.go
> +func (s *webServer) Dologin() {
请为导出函数添加注释，Thx

2021-02-09 14:29 UTC, Ink-33 approved these changes

2021-02-11 07:40 UTC, Ink-33 requested changes

2021-02-11 07:40 UTC, Ink-33 commented on server/apiAdmin.go
> +	coolq.SplitUrl = s.Conf.FixURL
请修改为coolq.SplitURL

2021-02-11 07:45 UTC, qianjunakasumi commented on server/apiAdmin.go
> +	coolq.SplitUrl = s.Conf.FixURL
合的时候大意了（

2021-02-16 09:58 UTC, Mrs4s approved these changes

2021-02-16 09:58 UTC, merged