让更多人知道如何有效、准确地提出 Issues
Mrs4s/go-cqhttp pull request #632
Opened 2021-02-12 16:38 UTC by qianjunakasumi

引入书籍：[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

2021-02-12 16:39 UTC, sam01101 commented
妙啊

2021-02-12 16:39 UTC, sam01101 approved these changes

2021-02-12 16:40 UTC, Ink-33 approved these changes
快快，一瞬合并

2021-02-15 06:33 UTC, sam01101 requested changes

2021-02-15 06:33 UTC, sam01101 commented on .github/ISSUE_TEMPLATE/bug--.md
>  4: 如果涉及内存泄漏/CPU占用异常请打开DEBUG模式并下载pprof性能分析.
可不可以在这里加插一行
`5: 请确保你已经阅读"提问前需知 [图+文]": https://github.com/Mrs4s/go-cqhttp/issues/633`
如果可以, 我觉得可以让他们勾起来的

2021-02-15 07:13 UTC, sam01101 approved these changes

2021-02-17 09:17 UTC, Mrs4s approved these changes

2021-02-17 09:17 UTC, merged

2021-02-18 16:21 UTC, qianjunakasumi commented
> 可不可以在这里加插一行
> `5: 请确保你已经阅读"提问前需知 [图+文]": https://github.com/Mrs4s/go-cqhttp/issues/633`
> 如果可以, 我觉得可以让他们勾起来的

忘记用代码片段了，现在他们新建Issue都会提及`#633`了（ @sam01101 

![image](https://user-images.githubusercontent.com/53565118/108386589-c1869800-7247-11eb-9eb1-94fac8d8dfc4.png)

2021-02-18 16:54 UTC, sam01101 commented
> > 可不可以在这里加插一行
> > `5: 请确保你已经阅读"提问前需知 [图+文]": https://github.com/Mrs4s/go-cqhttp/issues/633`
> > 如果可以, 我觉得可以让他们勾起来的
> 
> 忘记用代码片段了，现在他们新建Issue都会提及`#633`了（ @sam01101 
> 
> ![image](https://user-images.githubusercontent.com/53565118/108386589-c1869800-7247-11eb-9eb1-94fac8d8dfc4.png)
> 

这个其实还好，至少没人会骚扰到（