修复bug&更正代码
Mrs4s/go-cqhttp pull request #686
Opened 2021-03-01 13:51 UTC by sam01101

- `SendGroupForwardMessage` 添加发送失败Handler
- 禁言逻辑修复, 可以进行30(整)天的禁言
- 添加无法撤回临时信息Handling
- 临时会话中的变量改名 (code -> groupId)
- 临时会话发送与接收信息入库 (唯独没法加InternalId)
- 警告信息添加空格 (见cqcode.go)
- 为自定义reply添加seq选项以加真实性
- 更新文档: 添加seq说明, 缩短某个网址, 添加某个`CQcode`定义的导向

2021-03-01 14:04 UTC, Ink-33 requested changes

2021-03-01 14:04 UTC, Ink-33 commented on docs/cqhttp.md
> +| `messages` | forward node[] | 自定义转发消息, 具体看 [CQCode](https://github.com/sam01101/go-cqhttp/blob/master/docs/cqhttp.md#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E6%B6%88%E6%81%AF%E8%8A%82%E7%82%B9) |
链接是不是错了

2021-03-01 14:05 UTC, sam01101 commented on docs/cqhttp.md
> +| `messages` | forward node[] | 自定义转发消息, 具体看 [CQCode](https://github.com/sam01101/go-cqhttp/blob/master/docs/cqhttp.md#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E6%B6%88%E6%81%AF%E8%8A%82%E7%82%B9) |
写错Repo草

2021-03-01 15:19 UTC, sam01101 commented
close #495

2021-03-01 19:10 UTC, sam01101 commented
yamero!!!

2021-03-01 21:02 UTC, sam01101 commented on coolq/bot.go
> +		// FIXME(InsertTempMessage) InternalId missing
可以考虑在找到临时会话撤回信息的方法后移除

2021-03-02 15:25 UTC, sam01101 commented
呜呜呜Merge一下很难吗
我也想要Commit

2021-03-02 16:10 UTC, Mrs4s approved these changes

2021-03-02 16:10 UTC, merged