clean_cache接口的实现
Mrs4s/go-cqhttp pull request #749
Opened 2021-03-21 10:23 UTC by xuthus5

对正在使用的缓存文件，将其path写入一个map，以在遍历删除时判断当前缓存文件路径是否在map中的方式来进行操作删除操作。

2021-03-21 10:27 UTC, sam01101 commented
![Uploading image.png…]()

2021-03-21 10:28 UTC, sam01101 commented
![image](https://user-images.githubusercontent.com/25792361/111901427-29ace180-8a73-11eb-852b-8c4098acc297.png)

2021-03-21 10:30 UTC, sam01101 commented
> 对正在使用的缓存文件，将其path写入一个map，以在遍历删除时判断当前缓存文件路径是否在map中的方式来进行操作删除操作。

我这里给一些建议, 因为这样会引起内存开销, 如果这个功能简化成单单清除缓存文件即可
实现的方法可能就是读取缓存文件的路径然后全部删除

2021-03-21 10:32 UTC, xuthus5 commented
> > 对正在使用的缓存文件，将其path写入一个map，以在遍历删除时判断当前缓存文件路径是否在map中的方式来进行操作删除操作。
> 
> 我这里给一些建议, 因为这样会引起内存开销, 如果这个功能简化成单单清除缓存文件即可
> 实现的方法可能就是读取缓存文件的路径然后全部删除

当某个接口正在使用缓存文件，此时恰好该文件被删除，会触发某些异常。

2021-03-21 10:35 UTC, sam01101 commented
![Uploading image.png…]()

2021-03-21 10:35 UTC, sam01101 commented
![image](https://user-images.githubusercontent.com/25792361/111901617-38e05f00-8a74-11eb-9871-1b1b8b73d337.png)

2021-03-21 10:36 UTC, Ink-33 commented
![729c107f4d83924d.jpg](https://user-images.githubusercontent.com/51873347/111901633-51507980-8a74-11eb-9281-90a1a262dcc3.jpg)

2021-03-21 10:41 UTC, wdvxdr1123 commented
为了方便开发，请将推送分支修改为dev

2021-03-21 10:44 UTC, sam01101 commented
请在
>对正在使用的缓存文件，将其path写入一个map，以在遍历删除时判断当前缓存文件路径是否在map中的方式来进行操作删除操作。
下面添加以下文字以便issue自动close:
Closes #732

2021-03-21 10:52 UTC, wdvxdr1123 commented on global/mcache.go
> +	defer c.Lock.Unlock()
这里解锁前应该须要用waitgroup等待清理完成

2021-03-21 11:02 UTC, xuthus5 commented on global/mcache.go
> +	defer c.Lock.Unlock()
加上后鲁棒性变高了，但增加了该接口的等待时间。批量文件的io，个人认为使用异步即可，服务端只需要告诉你已经接受到了请求，什么时候处理完由服务端环境来决定。

2021-03-21 15:03 UTC, wdvxdr1123 requested changes

2021-03-21 15:03 UTC, wdvxdr1123 commented on global/mcache.go
> +}
sync.Map保证了协程安全，无需再次加锁

2021-03-21 15:03 UTC, wdvxdr1123 commented on global/mcache.go
> +	c.CacheMap.Delete(key)
同上

2021-03-22 03:53 UTC, xuthus5 commented on global/mcache.go
> +	c.CacheMap.Delete(key)
sync.map用来保证线程安全，另外加锁用来保证执行时序导致的问题。当执行清除缓存文件时，对写入缓存的操作进行阻塞

2021-03-22 08:17 UTC, wdvxdr1123 commented on global/mcache.go
> +	defer c.Lock.Unlock()
> sync.map用来保证线程安全，另外加锁用来保证执行时序导致的问题。当执行清除缓存文件时，对写入缓存的操作进行阻塞

在这里并没有保证解锁时已完成清空缓存

2021-03-22 10:54 UTC, xuthus5 commented on global/mcache.go
> +	defer c.Lock.Unlock()
确实有必要wait()了，否则无法避免接口重入带来的问题。

2021-04-05 12:30 UTC, sam01101 commented on global/mcache.go
> +	c.CacheMap.Delete(key)
@xuthus5 我建议你改一下以便PR
还有, 你的文件冲突了, 解决一下
![image](https://user-images.githubusercontent.com/25792361/113573979-ca8fc500-964d-11eb-83b1-f204a3d7b289.png)

2021-04-11 08:21 UTC, wdvxdr1123 commented
Files Changed里可以看到具体的失败信息

2021-04-11 08:27 UTC, xuthus5 commented
> Files Changed里可以看到具体的失败信息

ok，谢谢提醒。已经裂开了。

2021-04-21 00:13 UTC, sam01101 commented
10 天，我裂开了

2021-04-29 13:29 UTC, wdvxdr1123 commented
实现似乎有些复杂了

2021-10-20 06:21 UTC, remiliacn commented
nit：能不能rebase一下把commit整理一下，好多commit看着头疼（

2024-04-30 12:34 UTC, closed without merging