enhance linter
Mrs4s/go-cqhttp pull request #793
Opened 2021-04-04 17:04 UTC by Ink-33

**重塑` 0 warning `荣光，我辈义不容辞**

2021-04-04 18:01 UTC, sam01101 approved these changes
好!

2021-04-05 03:25 UTC, wdvxdr1123 commented on coolq/bot.go
> +		err = f.Close()
对于这些Close来说，并不需要错误信息，我觉得把他们加入ignore会更好

2021-04-05 03:39 UTC, Mrs4s requested changes

2021-04-05 03:39 UTC, Mrs4s commented on coolq/bot.go
> +		defer func() {
这类Close的err可以直接忽略 如 `defer func() {_ = video.Close()}()`

2021-04-05 03:40 UTC, wdvxdr1123 commented on coolq/bot.go
> +		defer func() {
### EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
- Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not check

可以把这条规则加入ignore中

2021-04-05 05:47 UTC, Ink-33 commented
force push 了

2021-04-05 07:14 UTC, merged