at, reply 添加更多细节
Mrs4s/go-cqhttp pull request #799
Opened 2021-04-05 19:50 UTC by sam01101

更改:
- 发送: 自定义reply可以用id了
- 发送: CQ:at 中的QQ如果不存在会使用name的field作为补偿
添加可选选项:
- 接收: 添加延申reply信息
- 删除回复消息中重复的艾特 (Closes #764)

2021-04-05 20:14 UTC, sam01101 commented
需要添加更多bug

2021-04-06 00:37 UTC, Mrs4s approved these changes

2021-04-06 00:37 UTC, Mrs4s commented on coolq/cqcode.go
> +				elem, err := e[i+1].(*message.AtElement)
这里需要做下边界检查, 否则会panic

2021-04-06 00:37 UTC, Mrs4s commented on coolq/cqcode.go
> +				elem, err := e[i+1].(*message.AtElement)
变量命名改为 `ok` 比较好

2021-04-06 00:37 UTC, Mrs4s commented on coolq/cqcode.go
> +					if senderErr != nil {
这地方上面已经判断过 `senderErr` 了, 不需要重复判断.

2021-04-06 00:38 UTC, Mrs4s requested changes
草 选错了

2021-04-06 09:23 UTC, sam01101 commented on coolq/cqcode.go
> +					return
添加 `senderErr` 判断的原因是因为这里有可能用户会输入`id`从数据库获取`uin`, 他们可以不给`qq`的field的

2021-04-06 09:27 UTC, Mrs4s requested changes

2021-04-06 09:27 UTC, Mrs4s commented on coolq/cqcode.go
> +			if conf.Message.RemoveReplyAt && len(e) > 1 {
这地方不能直接判断 `len(e) > 1`,  因为有可能 `reply` 元素不一定在消息头.

2021-04-06 09:30 UTC, sam01101 commented on coolq/cqcode.go
> +			if conf.Message.RemoveReplyAt && len(e) > 1 {
![image](https://user-images.githubusercontent.com/25792361/113690171-b4414200-96fd-11eb-8176-1283ce5c0528.png)
昵昵教我

2021-04-06 09:33 UTC, Mrs4s commented on coolq/cqcode.go
> +			if conf.Message.RemoveReplyAt && len(e) > 1 {
&& len(e) > i + 1

2021-04-06 09:35 UTC, sam01101 commented on coolq/cqcode.go
> +			if conf.Message.RemoveReplyAt && len(e) > 1 {
这个 `e[i+1] != nil` 是不是有同等效果

2021-04-06 09:36 UTC, Mrs4s commented on coolq/cqcode.go
> +			if conf.Message.RemoveReplyAt && len(e) > 1 {
会炸 这不是C语言

2021-04-06 09:42 UTC, sam01101 commented
应该没问题了

2021-04-06 09:47 UTC, wdvxdr1123 commented on coolq/cqcode.go
> +				msgTime, timeErr := strconv.ParseInt(e.Get("data").Get("time").String(), 10, 64)
此处可简化为Get("data.time")

2021-04-06 09:47 UTC, wdvxdr1123 commented on coolq/cqcode.go
> +				messageSeq, seqErr := strconv.ParseInt(e.Get("data").Get("seq").String(), 10, 64)
同上

2021-04-06 09:50 UTC, sam01101 commented
全部解决了

2021-04-06 10:50 UTC, wdvxdr1123 requested changes

2021-04-06 10:50 UTC, wdvxdr1123 commented on coolq/cqcode.go
> +				CQCodeEscapeValue(CQCodeEscapeText(ToStringMessage(replyElem.Elements, id))))
需要对array格式做相同处理

2021-04-06 10:50 UTC, wdvxdr1123 commented on coolq/cqcode.go
> +					log.Warnf("警告: 自定义 Reply 元素中必须包含 Uin 或 id")
此处应改为err != nil

2021-04-06 10:50 UTC, wdvxdr1123 commented on coolq/cqcode.go
> +			} else if err == nil {
应该加上err != nil时的处理

2021-04-06 11:06 UTC, sam01101 commented on coolq/cqcode.go
> +			} else if err == nil {
![image](https://user-images.githubusercontent.com/25792361/113701817-384df680-970b-11eb-97e0-d14d8f1c3375.png)

2021-04-06 11:49 UTC, sam01101 commented
![image](https://user-images.githubusercontent.com/25792361/113706356-2cfdc980-9711-11eb-87ae-ac68943f7770.png)
![image](https://user-images.githubusercontent.com/25792361/113706413-3c7d1280-9711-11eb-94d0-bc18bd624f4a.png)

2021-04-06 11:54 UTC, xiangxiangxiong9 commented
> ![image](https://user-images.githubusercontent.com/25792361/113706356-2cfdc980-9711-11eb-87ae-ac68943f7770.png)
> ![image](https://user-images.githubusercontent.com/25792361/113706413-3c7d1280-9711-11eb-94d0-bc18bd624f4a.png)

好多强制推送... 0.0 [试图对本地分支patch]

2021-04-06 12:56 UTC, sam01101 commented
再看下有无问题, 估计没问题了就可以Merge了

2021-04-06 13:22 UTC, merged